// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package database

import (
	"database/sql"
	"time"
)

type Album struct {
	Name      string
	Year      sql.NullInt64
	Rating    float64
	ArtistUrl string
	ImageUrl  sql.NullString
	PageURL   string
}

type Artist struct {
	Url          string
	Name         string
	Bio          sql.NullString
	ImageUrl     sql.NullString
	LastModified time.Time
}

type RelatedArtists struct {
	A string
	B string
}

type UpdateHistory struct {
	CheckedOn time.Time
	Hash      string
	PageURL   string
}
