FROM golang:1.21.4-alpine3.18 AS builder

WORKDIR /base

RUN apk add build-base

COPY app/updater/go.mod .
COPY app/updater/go.sum .

RUN go mod download

COPY app/updater/ ./


RUN CGO_ENABLED=1 go build -o ./updater-exe cmd/main.go

FROM alpine:3.18.5

WORKDIR /app

RUN ls

COPY --from=builder /base/updater-exe ./

RUN ls -al /app

ENV SERVER_PORT 8002
ENV SERVER_HOST "0.0.0.0"

EXPOSE ${SERVER_PORT}


CMD exec /app/updater-exe
