psql:
    image: postgres:alpine
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=apassword
      - POSTGRES_DB=scaruffi

service:
  build: .
  links:
    - psql:db
  ports:
    - "8080:8001"
  environment:
    - PORT=8001
    - PG_DATABASE=scaruffi
    - PG_HOST=db
    - PG_POST=5432
    - PG_USER=postgres
    - PG_PASSWORD=apassword
