// Code generated by tygo. DO NOT EDIT.

//////////
// source: types.go

export interface ArtistResult {
  id: string;
  name: string;
  imageURL?: string;
  confidence: number /* int */;
}
export interface AlbumResult {
  id: string;
  artistName: string;
  name: string;
  coverURL?: string;
  releaseYear?: number /* int */;
  confidence: number /* int */;
}
