// Code generated by tygo. DO NOT EDIT.

//////////
// source: types.go

export interface UpdateStatus {
  isUpdating: boolean;
  updateStart?: string;
  updateEnd?: string;
  artists: number /* int */;
  albums: number /* int */;
  pages: number /* int */;
  errors: string[];
}
