name: Build and deploy updater

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'app/updater/**'


env:
  REGISTRY: ghcr.io

jobs:
  build:
    name: Build server container and deploy
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      packages: write
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and publish
      uses: docker/build-push-action@v5
      with:
        context: ./
        push: true
        file: Dockerfile.updater
        tags: ghcr.io/waelbendhia/scruffy-updater:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Pull and restart containers
      uses: appleboy/ssh-action@v1.0.0
      env:
        COMPOSE_DIRECTORY: ${{ secrets.COMPOSE_DIRECTORY }}
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        envs: COMPOSE_DIRECTORY
        script: |
          echo "using directory: ${COMPOSE_DIRECTORY}"
          docker compose --project-directory "${COMPOSE_DIRECTORY}" down scruffy-updater
          docker compose --project-directory "${COMPOSE_DIRECTORY}" pull scruffy-updater
          docker compose --project-directory "${COMPOSE_DIRECTORY}" up scruffy-updater -d
